name: Lint and Test Project

on: [push]

jobs:
  Lint-the-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint the code!
        run: npm run lint